# tutorial: https://dev.to/zirkelc/trigger-github-workflow-for-comment-on-pull-request-45l2
name: changelog-edited

on: pull_request

jobs:
 changelog-edited:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # TODO: set master/main depending on which is the default branch
    - name: Check CHANGELOG.md
      id: check
      run: |
        # MAIN_BRANCH=main
        # git pull origin $MAIN_BRANCH
        git fetch --depth=1 origin main:main

        CHANGELOG_DIFF=$(git diff main CHANGELOG.md)
        echo "CHANGELOG_DIFF=somediff" >> $GITHUB_OUTPUT

        if [[ -z CHANGELOG_DIFF ]]
        then
            echo "CHANGELOG.md has **not** been edited..."
            echo "CHANGELOG_EDITED=0" >> $GITHUB_OUTPUT
        else
            echo "CHANGELOG.md has been edited..."
            echo "CHANGELOG_EDITED=1" >> $GITHUB_OUTPUT
        fi

    - name: Add comment to PR
      uses: actions/github-script@v6
      if: always()
      with:
        script: |
          const changelog_edited = '${{ steps.check.outputs.CHANGELOG_EDITED }}' == '1'

          if (!changelog_edited){
            const diff = '${{ steps.check.outputs.CHANGELOG_DIFF }}'
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Changelog hasn't been edited!"
            })
          } else {
            console.log("CHANGELOG has ben edited...")
          }


